@startuml

class Manu {}

class Minecraft extends Manu {}

class MC_JAVA extends Minecraft {}

class MCPE extends Minecraft {}

class Pokemon extends Manu {}

class SAV_Manu_100 extends Pokemon {}

class MyBoy extends SAV_Manu_100 {}

class Pokemon_Esmeralda extends MyBoy {}

class Pokemon_Rojo_Fuego extends MyBoy {}

class Nintendo3DS extends SAV_Manu_100 {}

class Pokemon_Blanco_y_Negro extends Nintendo3DS {}

class Pokemon_Diamante extends Nintendo3DS {}

class Pokemon_Oro_HeartGold extends Nintendo3DS {}

class Pokemon_Platino extends Nintendo3DS {}

@enduml